import type {
  BusinessProfileInput,
  GrantInput,
  SourceSiteInput,
  DiscoveredItemInput,
} from "./types";

export const SAMPLE_PROFILES: BusinessProfileInput[] = [
  {
    name: "カード事業部",
    entity_type: "株式会社",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市", "岐阜県", "岐阜市"],
    industries: ["小売", "EC", "イベント", "トレーディングカード"],
    description: "トレーディングカードの店舗販売・EC・大会イベント運営。",
    purposes: ["店舗改装", "空調設備", "EC強化", "POS導入", "在庫管理", "AI導入", "防犯カメラ", "イベント開催", "社員教育", "省力化", "DX"],
    expenses: ["設備費", "内装工事費", "システム導入費", "広告宣伝費", "機械装置費"],
    keywords: ["トレカ", "カードショップ", "中古販売"],
    exclude_keywords: ["農業", "漁業"],
    desired_amount: 1_000_000,
    notes: "店舗とECの両輪。イベント集客にも投資したい。",
  },
  {
    name: "美容サロン",
    entity_type: "株式会社",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市"],
    industries: ["美容", "サービス業"],
    description: "ヘア・エステの美容サロン運営。",
    purposes: ["設備導入", "内装工事", "予約システム", "広告宣伝", "社員教育", "DX"],
    expenses: ["設備費", "内装工事費", "システム導入費", "広告宣伝費", "研修費"],
    keywords: ["サロン", "美容室", "予約"],
    exclude_keywords: [],
    desired_amount: 1_000_000,
    notes: "内装刷新と予約システム導入を検討中。",
  },
  {
    name: "一般社団法人",
    entity_type: "一般社団法人",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市", "全国"],
    industries: ["サービス業", "医療・福祉", "教育・学習支援"],
    description: "地域の健康支援・講座・コミュニティ形成を行う一般社団法人。",
    purposes: ["地域活動", "健康支援", "イベント開催", "ホームページ制作", "広告宣伝"],
    expenses: ["委託費", "広告宣伝費", "人件費", "研修費", "外注費"],
    keywords: ["健康", "予防医療", "食育", "コミュニティ", "講座"],
    exclude_keywords: [],
    desired_amount: 2_000_000,
    notes: "助成金中心。非営利向けの制度を重視。",
  },
  {
    name: "食品・EC事業",
    entity_type: "株式会社",
    location: "岐阜県",
    regions: ["岐阜県", "愛知県", "全国"],
    industries: ["食品", "EC", "小売", "地域産品"],
    description: "地域産品の加工・EC販売・販路開拓。",
    purposes: ["販路開拓", "EC強化", "商品開発", "広告宣伝", "輸出"],
    expenses: ["広告宣伝費", "システム導入費", "委託費", "機械装置費", "開発費"],
    keywords: ["食品", "地域産品", "通販", "ふるさと"],
    exclude_keywords: [],
    desired_amount: 1_500_000,
    notes: "ECと販路開拓に投資したい。",
  },
  {
    name: "AI・システム開発事業",
    entity_type: "株式会社",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市", "全国"],
    industries: ["IT", "AI", "DX", "システム開発", "情報通信"],
    description: "受託・自社のAI/システム開発、DX支援。",
    purposes: ["AI導入", "業務自動化", "研究開発", "DX", "省力化"],
    expenses: ["システム導入費", "ソフトウェア費", "開発費", "外注費", "人件費"],
    keywords: ["AI", "DX", "自動化", "SaaS"],
    exclude_keywords: [],
    desired_amount: 3_000_000,
    notes: "研究開発・DX関連の制度を重視。",
  },
];

const today = new Date();
function dateAfter(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const SAMPLE_GRANTS: GrantInput[] = [
  {
    name: "小規模事業者持続化補助金（店舗改装枠・サンプル）",
    grant_type: "補助金",
    organization: "サンプル商工会議所",
    org_type: "国",
    regions: ["全国"],
    industries: ["小売", "サービス業", "飲食", "美容"],
    entity_types: ["株式会社", "個人事業主", "合同会社"],
    target_audience: "小規模事業者",
    expense_categories: ["内装工事費", "設備費", "広告宣伝費"],
    subsidy_rate: "2/3",
    min_amount: 500_000,
    max_amount: 2_000_000,
    application_start: dateAfter(-20),
    application_deadline: dateAfter(20),
    recruitment_status: "募集中",
    application_method: "電子申請（サンプル）",
    required_documents: "事業計画書、経費明細、見積書",
    official_url: "https://example.com/jizokuka",
    guideline_pdf_url: "https://example.com/jizokuka.pdf",
    notes: "店舗の改装・販促に幅広く使える定番枠（サンプル）。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["店舗改装", "販路開拓", "持続化"],
    purposes: ["店舗改装", "内装工事", "広告宣伝", "販路開拓", "新店舗出店"],
    exclusion_conditions: "創業前の事業は対象外（サンプル）。",
    early_termination_risk: false,
    selection_type: "採択制",
    difficulty: "中",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "IT導入補助金（DX推進枠・サンプル）",
    grant_type: "補助金",
    organization: "サンプル中小企業庁",
    org_type: "国",
    regions: ["全国"],
    industries: ["全業種"],
    entity_types: [],
    target_audience: "中小企業・小規模事業者",
    expense_categories: ["システム導入費", "ソフトウェア費", "委託費"],
    subsidy_rate: "1/2〜3/4",
    min_amount: 300_000,
    max_amount: 4_500_000,
    application_start: dateAfter(-30),
    application_deadline: dateAfter(45),
    recruitment_status: "募集中",
    application_method: "GビズID＋電子申請（サンプル）",
    required_documents: "gBizIDプライム、SECURITY ACTION宣言",
    official_url: "https://example.com/it-hojo",
    guideline_pdf_url: "https://example.com/it-hojo.pdf",
    notes: "POS・予約・在庫・ECなどITツール導入に使える（サンプル）。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["IT", "DX", "POS", "予約システム", "EC"],
    purposes: ["DX", "POS導入", "在庫管理", "予約システム", "EC強化", "AI導入", "業務自動化", "省力化"],
    exclusion_conditions: "登録IT導入支援事業者のツールに限る（サンプル）。",
    early_termination_risk: true,
    selection_type: "採択制",
    difficulty: "中",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "省エネ設備導入補助金（空調更新・サンプル）",
    grant_type: "補助金",
    organization: "サンプル環境財団",
    org_type: "財団系",
    regions: ["愛知県", "岐阜県"],
    industries: ["全業種"],
    entity_types: [],
    target_audience: "中小事業者",
    expense_categories: ["設備費", "機械装置費"],
    subsidy_rate: "1/3",
    min_amount: 200_000,
    max_amount: 1_000_000,
    application_start: dateAfter(-10),
    application_deadline: dateAfter(10),
    recruitment_status: "募集中",
    application_method: "郵送（サンプル）",
    required_documents: "省エネ計算書、見積書",
    official_url: "https://example.com/shouene",
    guideline_pdf_url: null,
    notes: "高効率空調・LEDなどへの更新が対象（サンプル）。締切が近い。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["省エネ", "空調", "LED"],
    purposes: ["省エネ", "空調設備", "設備導入"],
    exclusion_conditions: "中古設備は対象外（サンプル）。",
    early_termination_risk: true,
    selection_type: "条件達成型",
    difficulty: "低",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "人材開発支援助成金（研修・サンプル）",
    grant_type: "助成金",
    organization: "サンプル労働局",
    org_type: "厚労省系",
    regions: ["全国"],
    industries: ["全業種"],
    entity_types: ["株式会社", "合同会社", "一般社団法人"],
    target_audience: "雇用保険適用事業所",
    expense_categories: ["研修費", "人件費"],
    subsidy_rate: "45〜75%",
    min_amount: null,
    max_amount: 1_000_000,
    application_start: dateAfter(-60),
    application_deadline: null,
    recruitment_status: "募集中",
    application_method: "労働局へ計画届提出（サンプル）",
    required_documents: "訓練計画届、就業規則",
    official_url: "https://example.com/jinzai",
    guideline_pdf_url: "https://example.com/jinzai.pdf",
    notes: "社員研修・OJTに使える助成金（サンプル）。計画届の事前提出が必要。",
    pre_application_ng: true,
    requires_professional: true,
    keywords: ["研修", "人材育成", "教育訓練"],
    purposes: ["社員教育", "スタッフ採用"],
    exclusion_conditions: "計画届提出前に開始した訓練は対象外（サンプル）。",
    early_termination_risk: false,
    selection_type: "条件達成型",
    difficulty: "高",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "地域づくり活動助成（イベント・サンプル）",
    grant_type: "助成金",
    organization: "サンプル地域財団",
    org_type: "財団系",
    regions: ["愛知県", "名古屋市"],
    industries: ["全業種"],
    entity_types: ["一般社団法人", "NPO法人", "公益社団法人"],
    target_audience: "非営利団体・地域団体",
    expense_categories: ["委託費", "広告宣伝費", "外注費"],
    subsidy_rate: "定額",
    min_amount: null,
    max_amount: 500_000,
    application_start: dateAfter(-5),
    application_deadline: dateAfter(60),
    recruitment_status: "募集中",
    application_method: "オンライン申請（サンプル）",
    required_documents: "事業計画、収支予算書",
    official_url: "https://example.com/chiiki",
    guideline_pdf_url: null,
    notes: "地域の健康・コミュニティイベント向け（サンプル）。",
    pre_application_ng: false,
    requires_professional: false,
    keywords: ["地域", "イベント", "健康", "コミュニティ"],
    purposes: ["地域活動", "健康支援", "イベント開催"],
    exclusion_conditions: "営利目的の事業は対象外（サンプル）。",
    early_termination_risk: false,
    selection_type: "採択制",
    difficulty: "低",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "EC・販路開拓支援補助金（サンプル）",
    grant_type: "補助金",
    organization: "サンプル県産業振興公社",
    org_type: "自治体",
    regions: ["岐阜県", "愛知県"],
    industries: ["食品", "小売", "EC", "地域産品", "製造業"],
    entity_types: [],
    target_audience: "県内の中小事業者",
    expense_categories: ["広告宣伝費", "システム導入費", "委託費", "開発費"],
    subsidy_rate: "1/2",
    min_amount: 100_000,
    max_amount: 1_500_000,
    application_start: dateAfter(-15),
    application_deadline: dateAfter(5),
    recruitment_status: "締切間近",
    application_method: "電子申請（サンプル）",
    required_documents: "販路開拓計画、見積書",
    official_url: "https://example.com/ec-hanro",
    guideline_pdf_url: "https://example.com/ec-hanro.pdf",
    notes: "ECサイト構築・展示会出展・越境ECに使える（サンプル）。まもなく締切。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["EC", "販路開拓", "越境EC", "展示会"],
    purposes: ["EC強化", "販路開拓", "商品開発", "広告宣伝", "輸出", "食品EC"],
    exclusion_conditions: "県外事業者は対象外（サンプル）。",
    early_termination_risk: true,
    selection_type: "採択制",
    difficulty: "中",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
];

// =============================================================
// 自動探索レーダー用サンプル：情報源（3層構造）と検知候補
// =============================================================

export const SAMPLE_SOURCE_SITES: SourceSiteInput[] = [
  {
    name: "中小企業庁（公式・サンプル）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.chusho.meti.go.jp/",
    region: "全国",
    priority: "high",
    crawl_frequency: "daily",
    is_active: true,
    last_checked_at: null,
    notes: "第1層：省庁の一次情報。最も信頼できる。",
  },
  {
    name: "愛知県 産業振興（公式・サンプル）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.pref.aichi.jp/",
    region: "愛知県",
    priority: "high",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "第1層：自治体公式。地方補助金の一次情報。",
  },
  {
    name: "J-Net21 支援情報ヘッドライン（準公式・サンプル）",
    source_type: "semi_official",
    trust_level: "B",
    url: "https://j-net21.smrj.go.jp/",
    region: "全国",
    priority: "high",
    crawl_frequency: "daily",
    is_active: true,
    last_checked_at: null,
    notes: "第2層：中小機構の準公式DB。比較的信頼できる支援情報。",
  },
  {
    name: "ミラサポplus（準公式・サンプル）",
    source_type: "semi_official",
    trust_level: "B",
    url: "https://mirasapo-plus.go.jp/",
    region: "全国",
    priority: "medium",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "第2層：中小企業向け支援情報の準公式サイト。",
  },
  {
    name: "補助金ポータル（民間まとめ・サンプル）",
    source_type: "aggregator",
    trust_level: "C",
    url: "https://example.com/hojokin-portal",
    region: "全国",
    priority: "medium",
    crawl_frequency: "daily",
    is_active: true,
    last_checked_at: null,
    notes: "第3層：民間まとめサイト。地方補助金の発見用レーダーとして使う（二次情報）。",
  },
  {
    name: "助成金なう（民間まとめ・サンプル）",
    source_type: "aggregator",
    trust_level: "C",
    url: "https://example.com/josdeingkin-now",
    region: "全国",
    priority: "low",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "第3層：民間まとめサイト。発見用。必ず公式で要確認。",
  },
  {
    name: "行政書士法人の補助金コラム（記事・サンプル）",
    source_type: "professional_article",
    trust_level: "D",
    url: "https://example.com/gyosei-column",
    region: "全国",
    priority: "low",
    crawl_frequency: "monthly",
    is_active: true,
    last_checked_at: null,
    notes: "第3層：士業の解説記事。発見の手がかり。一次情報ではない。",
  },
  {
    name: "PR TIMES 補助金関連リリース（ニュース・サンプル）",
    source_type: "news",
    trust_level: "D",
    url: "https://example.com/prtimes-hojokin",
    region: "全国",
    priority: "low",
    crawl_frequency: "weekly",
    is_active: false,
    last_checked_at: null,
    notes: "第3層：プレスリリース。新着の気づき用。要公式確認。",
  },
];

// 自動収集の対象：5地域の公式補助金一覧ページ（web で確認済みの実URL）。
// source_type=official / trust_level=A。/api/discovery/crawl の巡回対象になる。
export const SAMPLE_COLLECT_SOURCES: SourceSiteInput[] = [
  {
    name: "愛知県 助成金・補助金（公式）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.pref.aichi.jp/life/sub/2/",
    region: "愛知県",
    priority: "high",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "愛知県公式の助成金・補助金カテゴリ。事業者・個人の双方を含む。",
    audience_scope: "both",
  },
  {
    name: "名古屋市 事業者等への支援（公式）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.city.nagoya.jp/jigyou/sangyou/1026356/index.html",
    region: "名古屋市",
    priority: "high",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "名古屋市公式の事業者向け支援・補助の入口。",
    audience_scope: "business",
  },
  {
    name: "名古屋市 市の補助・助成制度（暮らし・公式）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.city.nagoya.jp/kurashi/juutaku/1014710/1043859/index.html",
    region: "名古屋市",
    priority: "medium",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "名古屋市公式の個人・暮らし向け補助・助成。",
    audience_scope: "individual",
  },
  {
    name: "岐阜県 補助金・優遇制度（公式）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.pref.gifu.lg.jp/life/sub/10/",
    region: "岐阜県",
    priority: "high",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "岐阜県公式の補助金・優遇制度カテゴリ。",
    audience_scope: "both",
  },
  {
    name: "岐阜市 補助金（公式）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.city.gifu.lg.jp/info/hojokin/index.html",
    region: "岐阜市",
    priority: "high",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "岐阜市公式の補助金インデックス。",
    audience_scope: "both",
  },
  {
    name: "弥富市 補助金等一覧（公式）",
    source_type: "official",
    trust_level: "A",
    url: "https://www.city.yatomi.lg.jp/kurashi/1006880/index.html",
    region: "弥富市",
    priority: "high",
    crawl_frequency: "weekly",
    is_active: true,
    last_checked_at: null,
    notes: "弥富市公式の補助金等一覧。",
    audience_scope: "both",
  },
  // J-Net21（中小機構の支援情報ヘッドライン）。
  //   調査結果（2026-06 時点）：公開RSS/Atom/CSV/API などの機械可読な一括取得手段は
  //   提供されておらず、構造的な配信は「新着情報メールマガジン（毎週火曜）」のみ。
  //   サイトはリンクフリー（出典明記を要請）だが、自動取得用フィードは無い。
  //   → 方針どおり「自動スクレイピングはせず」、情報源として登録＋手動取り込み導線のみ。
  //      is_active=false なので runAll の自動巡回対象から除外される。
  //      メルマガ取り込みは将来「メール受信取り込み」（feed ルートのコメント参照）で対応予定。
  {
    name: "J-Net21 支援情報ヘッドライン（中小機構・準公式）",
    source_type: "semi_official",
    trust_level: "B",
    url: "https://j-net21.smrj.go.jp/snavi/index.html",
    region: "全国",
    priority: "medium",
    crawl_frequency: "weekly",
    is_active: false,
    last_checked_at: null,
    notes:
      "公開フィード/API無し。自動巡回はせず手動取り込み。メルマガ（毎週火）はメール受信取り込みで将来対応。出典明記のうえ利用。",
    audience_scope: "business",
  },
];

// 検知候補のサンプル（source_site_id はシード時に紐づける／未紐づけでも可）
export const SAMPLE_DISCOVERED_ITEMS: Omit<DiscoveredItemInput, "source_site_id">[] = [
  {
    title: "【愛知県】小規模事業者向け 店舗改装支援補助金（令和7年度・サンプル）",
    url: "https://example.com/hojokin-portal/aichi-tenpo-kaisou",
    raw_text:
      "愛知県内の小規模事業者を対象に、店舗の改装・内装工事費用の一部を補助します。補助率2/3、上限200万円。対象経費は内装工事費、設備費、広告宣伝費など。募集中。交付決定前に着手した経費は対象外となるためご注意ください。詳しくは公式サイトをご確認ください。",
    raw_html: null,
    pdf_url: null,
    detection_type: "new",
    status: "unreviewed",
    source_category: "aggregator",
    trust_level: "C",
    original_source_url: "https://example.com/hojokin-portal/aichi-tenpo-kaisou",
    official_url: null,
    official_pdf_url: null,
    official_source_confirmed: false,
    source_warning: null,
    last_verified_at: null,
    verification_status: "unverified",
    duplicate_of: null,
  },
  {
    title: "IT導入補助金 2025 公募開始のお知らせ（サンプル）",
    url: "https://www.chusho.meti.go.jp/example/it-hojo-2025",
    raw_text:
      "中小企業・小規模事業者を対象としたIT導入補助金の公募が開始されました。対象は全業種。補助率1/2〜3/4、上限450万円。システム導入費、ソフトウェア費が対象。締切は 2026/7/31。GビズID＋電子申請。",
    raw_html: null,
    pdf_url: "https://www.chusho.meti.go.jp/example/it-hojo-2025.pdf",
    detection_type: "new",
    status: "unreviewed",
    source_category: "official",
    trust_level: "A",
    original_source_url: "https://www.chusho.meti.go.jp/example/it-hojo-2025",
    official_url: "https://www.chusho.meti.go.jp/example/it-hojo-2025",
    official_pdf_url: "https://www.chusho.meti.go.jp/example/it-hojo-2025.pdf",
    official_source_confirmed: true,
    source_warning: null,
    last_verified_at: null,
    verification_status: "official_found",
    duplicate_of: null,
  },
  {
    title: "【記事】今年使える助成金まとめ｜社員研修に使える人材開発支援助成金とは（サンプル）",
    url: "https://example.com/gyosei-column/jinzai-kaihatsu",
    raw_text:
      "社員の研修・教育訓練にかかる費用の一部を助成する人材開発支援助成金について解説します。雇用保険適用事業所が対象。助成率は45〜75%。計画届の事前提出が必要で、社会保険労務士への相談がおすすめです。※本記事は概要の紹介であり、最新の要件は必ず公式でご確認ください。",
    raw_html: null,
    pdf_url: null,
    detection_type: "new",
    status: "unreviewed",
    source_category: "professional_article",
    trust_level: "D",
    original_source_url: "https://example.com/gyosei-column/jinzai-kaihatsu",
    official_url: null,
    official_pdf_url: null,
    official_source_confirmed: false,
    source_warning: null,
    last_verified_at: null,
    verification_status: "unverified",
    duplicate_of: null,
  },
];
