import type { BusinessProfileInput, GrantInput } from "./types";

export const SAMPLE_PROFILES: BusinessProfileInput[] = [
  {
    name: "カード事業部",
    entity_type: "株式会社",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市", "岐阜県", "岐阜市"],
    industries: ["小売", "EC", "イベント", "トレーディングカード"],
    description: "トレーディングカードの店舗販売・EC・大会イベント運営。",
    purposes: ["店舗改装", "空調設備", "EC強化", "POS導入", "在庫管理", "AI導入", "防犯カメラ", "イベント開催", "社員教育", "省力化", "DX"],
    expenses: ["設備費", "内装工事費", "システム導入費", "広告宣伝費", "機械装置費"],
    keywords: ["トレカ", "カードショップ", "中古販売"],
    exclude_keywords: ["農業", "漁業"],
    desired_amount: 1_000_000,
    notes: "店舗とECの両輪。イベント集客にも投資したい。",
  },
  {
    name: "美容サロン",
    entity_type: "株式会社",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市"],
    industries: ["美容", "サービス業"],
    description: "ヘア・エステの美容サロン運営。",
    purposes: ["設備導入", "内装工事", "予約システム", "広告宣伝", "社員教育", "DX"],
    expenses: ["設備費", "内装工事費", "システム導入費", "広告宣伝費", "研修費"],
    keywords: ["サロン", "美容室", "予約"],
    exclude_keywords: [],
    desired_amount: 1_000_000,
    notes: "内装刷新と予約システム導入を検討中。",
  },
  {
    name: "一般社団法人",
    entity_type: "一般社団法人",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市", "全国"],
    industries: ["サービス業", "医療・福祉", "教育・学習支援"],
    description: "地域の健康支援・講座・コミュニティ形成を行う一般社団法人。",
    purposes: ["地域活動", "健康支援", "イベント開催", "ホームページ制作", "広告宣伝"],
    expenses: ["委託費", "広告宣伝費", "人件費", "研修費", "外注費"],
    keywords: ["健康", "予防医療", "食育", "コミュニティ", "講座"],
    exclude_keywords: [],
    desired_amount: 2_000_000,
    notes: "助成金中心。非営利向けの制度を重視。",
  },
  {
    name: "食品・EC事業",
    entity_type: "株式会社",
    location: "岐阜県",
    regions: ["岐阜県", "愛知県", "全国"],
    industries: ["食品", "EC", "小売", "地域産品"],
    description: "地域産品の加工・EC販売・販路開拓。",
    purposes: ["販路開拓", "EC強化", "商品開発", "広告宣伝", "輸出"],
    expenses: ["広告宣伝費", "システム導入費", "委託費", "機械装置費", "開発費"],
    keywords: ["食品", "地域産品", "通販", "ふるさと"],
    exclude_keywords: [],
    desired_amount: 1_500_000,
    notes: "ECと販路開拓に投資したい。",
  },
  {
    name: "AI・システム開発事業",
    entity_type: "株式会社",
    location: "名古屋市",
    regions: ["愛知県", "名古屋市", "全国"],
    industries: ["IT", "AI", "DX", "システム開発", "情報通信"],
    description: "受託・自社のAI/システム開発、DX支援。",
    purposes: ["AI導入", "業務自動化", "研究開発", "DX", "省力化"],
    expenses: ["システム導入費", "ソフトウェア費", "開発費", "外注費", "人件費"],
    keywords: ["AI", "DX", "自動化", "SaaS"],
    exclude_keywords: [],
    desired_amount: 3_000_000,
    notes: "研究開発・DX関連の制度を重視。",
  },
];

const today = new Date();
function dateAfter(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const SAMPLE_GRANTS: GrantInput[] = [
  {
    name: "小規模事業者持続化補助金（店舗改装枠・サンプル）",
    grant_type: "補助金",
    organization: "サンプル商工会議所",
    org_type: "国",
    regions: ["全国"],
    industries: ["小売", "サービス業", "飲食", "美容"],
    entity_types: ["株式会社", "個人事業主", "合同会社"],
    target_audience: "小規模事業者",
    expense_categories: ["内装工事費", "設備費", "広告宣伝費"],
    subsidy_rate: "2/3",
    min_amount: 500_000,
    max_amount: 2_000_000,
    application_start: dateAfter(-20),
    application_deadline: dateAfter(20),
    recruitment_status: "募集中",
    application_method: "電子申請（サンプル）",
    required_documents: "事業計画書、経費明細、見積書",
    official_url: "https://example.com/jizokuka",
    guideline_pdf_url: "https://example.com/jizokuka.pdf",
    notes: "店舗の改装・販促に幅広く使える定番枠（サンプル）。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["店舗改装", "販路開拓", "持続化"],
    purposes: ["店舗改装", "内装工事", "広告宣伝", "販路開拓", "新店舗出店"],
    exclusion_conditions: "創業前の事業は対象外（サンプル）。",
    early_termination_risk: false,
    selection_type: "採択制",
    difficulty: "中",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "IT導入補助金（DX推進枠・サンプル）",
    grant_type: "補助金",
    organization: "サンプル中小企業庁",
    org_type: "国",
    regions: ["全国"],
    industries: ["全業種"],
    entity_types: [],
    target_audience: "中小企業・小規模事業者",
    expense_categories: ["システム導入費", "ソフトウェア費", "委託費"],
    subsidy_rate: "1/2〜3/4",
    min_amount: 300_000,
    max_amount: 4_500_000,
    application_start: dateAfter(-30),
    application_deadline: dateAfter(45),
    recruitment_status: "募集中",
    application_method: "GビズID＋電子申請（サンプル）",
    required_documents: "gBizIDプライム、SECURITY ACTION宣言",
    official_url: "https://example.com/it-hojo",
    guideline_pdf_url: "https://example.com/it-hojo.pdf",
    notes: "POS・予約・在庫・ECなどITツール導入に使える（サンプル）。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["IT", "DX", "POS", "予約システム", "EC"],
    purposes: ["DX", "POS導入", "在庫管理", "予約システム", "EC強化", "AI導入", "業務自動化", "省力化"],
    exclusion_conditions: "登録IT導入支援事業者のツールに限る（サンプル）。",
    early_termination_risk: true,
    selection_type: "採択制",
    difficulty: "中",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "省エネ設備導入補助金（空調更新・サンプル）",
    grant_type: "補助金",
    organization: "サンプル環境財団",
    org_type: "財団系",
    regions: ["愛知県", "岐阜県"],
    industries: ["全業種"],
    entity_types: [],
    target_audience: "中小事業者",
    expense_categories: ["設備費", "機械装置費"],
    subsidy_rate: "1/3",
    min_amount: 200_000,
    max_amount: 1_000_000,
    application_start: dateAfter(-10),
    application_deadline: dateAfter(10),
    recruitment_status: "募集中",
    application_method: "郵送（サンプル）",
    required_documents: "省エネ計算書、見積書",
    official_url: "https://example.com/shouene",
    guideline_pdf_url: null,
    notes: "高効率空調・LEDなどへの更新が対象（サンプル）。締切が近い。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["省エネ", "空調", "LED"],
    purposes: ["省エネ", "空調設備", "設備導入"],
    exclusion_conditions: "中古設備は対象外（サンプル）。",
    early_termination_risk: true,
    selection_type: "条件達成型",
    difficulty: "低",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "人材開発支援助成金（研修・サンプル）",
    grant_type: "助成金",
    organization: "サンプル労働局",
    org_type: "厚労省系",
    regions: ["全国"],
    industries: ["全業種"],
    entity_types: ["株式会社", "合同会社", "一般社団法人"],
    target_audience: "雇用保険適用事業所",
    expense_categories: ["研修費", "人件費"],
    subsidy_rate: "45〜75%",
    min_amount: null,
    max_amount: 1_000_000,
    application_start: dateAfter(-60),
    application_deadline: null,
    recruitment_status: "募集中",
    application_method: "労働局へ計画届提出（サンプル）",
    required_documents: "訓練計画届、就業規則",
    official_url: "https://example.com/jinzai",
    guideline_pdf_url: "https://example.com/jinzai.pdf",
    notes: "社員研修・OJTに使える助成金（サンプル）。計画届の事前提出が必要。",
    pre_application_ng: true,
    requires_professional: true,
    keywords: ["研修", "人材育成", "教育訓練"],
    purposes: ["社員教育", "スタッフ採用"],
    exclusion_conditions: "計画届提出前に開始した訓練は対象外（サンプル）。",
    early_termination_risk: false,
    selection_type: "条件達成型",
    difficulty: "高",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "地域づくり活動助成（イベント・サンプル）",
    grant_type: "助成金",
    organization: "サンプル地域財団",
    org_type: "財団系",
    regions: ["愛知県", "名古屋市"],
    industries: ["全業種"],
    entity_types: ["一般社団法人", "NPO法人", "公益社団法人"],
    target_audience: "非営利団体・地域団体",
    expense_categories: ["委託費", "広告宣伝費", "外注費"],
    subsidy_rate: "定額",
    min_amount: null,
    max_amount: 500_000,
    application_start: dateAfter(-5),
    application_deadline: dateAfter(60),
    recruitment_status: "募集中",
    application_method: "オンライン申請（サンプル）",
    required_documents: "事業計画、収支予算書",
    official_url: "https://example.com/chiiki",
    guideline_pdf_url: null,
    notes: "地域の健康・コミュニティイベント向け（サンプル）。",
    pre_application_ng: false,
    requires_professional: false,
    keywords: ["地域", "イベント", "健康", "コミュニティ"],
    purposes: ["地域活動", "健康支援", "イベント開催"],
    exclusion_conditions: "営利目的の事業は対象外（サンプル）。",
    early_termination_risk: false,
    selection_type: "採択制",
    difficulty: "低",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
  {
    name: "EC・販路開拓支援補助金（サンプル）",
    grant_type: "補助金",
    organization: "サンプル県産業振興公社",
    org_type: "自治体",
    regions: ["岐阜県", "愛知県"],
    industries: ["食品", "小売", "EC", "地域産品", "製造業"],
    entity_types: [],
    target_audience: "県内の中小事業者",
    expense_categories: ["広告宣伝費", "システム導入費", "委託費", "開発費"],
    subsidy_rate: "1/2",
    min_amount: 100_000,
    max_amount: 1_500_000,
    application_start: dateAfter(-15),
    application_deadline: dateAfter(5),
    recruitment_status: "締切間近",
    application_method: "電子申請（サンプル）",
    required_documents: "販路開拓計画、見積書",
    official_url: "https://example.com/ec-hanro",
    guideline_pdf_url: "https://example.com/ec-hanro.pdf",
    notes: "ECサイト構築・展示会出展・越境ECに使える（サンプル）。まもなく締切。",
    pre_application_ng: true,
    requires_professional: false,
    keywords: ["EC", "販路開拓", "越境EC", "展示会"],
    purposes: ["EC強化", "販路開拓", "商品開発", "広告宣伝", "輸出", "食品EC"],
    exclusion_conditions: "県外事業者は対象外（サンプル）。",
    early_termination_risk: true,
    selection_type: "採択制",
    difficulty: "中",
    source: "サンプル",
    fetched_at: new Date().toISOString(),
  },
];
