-- =============================================================
-- サンプルデータ（任意）
-- 注意：アプリ内の「サンプル登録」ボタンを使うと、登録と同時に
--       全事業との自動照合・アラート作成まで行われます（推奨）。
-- このSQLで投入した場合は、各補助金の詳細ページで「全事業を再照合」を
-- 押すと grant_matches / alerts が生成されます。
-- =============================================================

-- 事業プロフィール5件
insert into business_profiles (name, entity_type, location, regions, industries, description, purposes, expenses, keywords, exclude_keywords, desired_amount, notes) values
('カード事業部','株式会社','名古屋市',
 array['愛知県','名古屋市','岐阜県','岐阜市'],
 array['小売','EC','イベント','トレーディングカード'],
 'トレーディングカードの店舗販売・EC・大会イベント運営。',
 array['店舗改装','空調設備','EC強化','POS導入','在庫管理','AI導入','防犯カメラ','イベント開催','社員教育','省力化','DX'],
 array['設備費','内装工事費','システム導入費','広告宣伝費','機械装置費'],
 array['トレカ','カードショップ','中古販売'], array['農業','漁業'], 1000000, '店舗とECの両輪。'),
('美容サロン','株式会社','名古屋市',
 array['愛知県','名古屋市'], array['美容','サービス業'],
 'ヘア・エステの美容サロン運営。',
 array['設備導入','内装工事','予約システム','広告宣伝','社員教育','DX'],
 array['設備費','内装工事費','システム導入費','広告宣伝費','研修費'],
 array['サロン','美容室','予約'], array[]::text[], 1000000, '内装刷新と予約システム導入を検討中。'),
('一般社団法人','一般社団法人','名古屋市',
 array['愛知県','名古屋市','全国'], array['サービス業','医療・福祉','教育・学習支援'],
 '地域の健康支援・講座・コミュニティ形成を行う一般社団法人。',
 array['地域活動','健康支援','イベント開催','ホームページ制作','広告宣伝'],
 array['委託費','広告宣伝費','人件費','研修費','外注費'],
 array['健康','予防医療','食育','コミュニティ','講座'], array[]::text[], 2000000, '助成金中心。'),
('食品・EC事業','株式会社','岐阜県',
 array['岐阜県','愛知県','全国'], array['食品','EC','小売','地域産品'],
 '地域産品の加工・EC販売・販路開拓。',
 array['販路開拓','EC強化','商品開発','広告宣伝','輸出'],
 array['広告宣伝費','システム導入費','委託費','機械装置費','開発費'],
 array['食品','地域産品','通販','ふるさと'], array[]::text[], 1500000, 'ECと販路開拓に投資したい。'),
('AI・システム開発事業','株式会社','名古屋市',
 array['愛知県','名古屋市','全国'], array['IT','AI','DX','システム開発','情報通信'],
 '受託・自社のAI/システム開発、DX支援。',
 array['AI導入','業務自動化','研究開発','DX','省力化'],
 array['システム導入費','ソフトウェア費','開発費','外注費','人件費'],
 array['AI','DX','自動化','SaaS'], array[]::text[], 3000000, '研究開発・DX関連を重視。');

-- 補助金6件（締切は実行日からの相対日付）
insert into grants (name, grant_type, organization, org_type, regions, industries, entity_types, target_audience, expense_categories, subsidy_rate, min_amount, max_amount, application_start, application_deadline, recruitment_status, application_method, required_documents, official_url, guideline_pdf_url, notes, pre_application_ng, requires_professional, keywords, purposes, exclusion_conditions, early_termination_risk, selection_type, difficulty, source, fetched_at) values
('小規模事業者持続化補助金（店舗改装枠・サンプル）','補助金','サンプル商工会議所','国',
 array['全国'], array['小売','サービス業','飲食','美容'], array['株式会社','個人事業主','合同会社'],
 '小規模事業者', array['内装工事費','設備費','広告宣伝費'], '2/3', 500000, 2000000,
 current_date - 20, current_date + 20, '募集中', '電子申請（サンプル）', '事業計画書、経費明細、見積書',
 'https://example.com/jizokuka','https://example.com/jizokuka.pdf','店舗の改装・販促に幅広く使える定番枠（サンプル）。',
 true, false, array['店舗改装','販路開拓','持続化'], array['店舗改装','内装工事','広告宣伝','販路開拓','新店舗出店'],
 '創業前の事業は対象外（サンプル）。', false, '採択制', '中', 'サンプル', now()),
('IT導入補助金（DX推進枠・サンプル）','補助金','サンプル中小企業庁','国',
 array['全国'], array['全業種'], array[]::text[],
 '中小企業・小規模事業者', array['システム導入費','ソフトウェア費','委託費'], '1/2〜3/4', 300000, 4500000,
 current_date - 30, current_date + 45, '募集中', 'GビズID＋電子申請（サンプル）', 'gBizIDプライム、SECURITY ACTION宣言',
 'https://example.com/it-hojo','https://example.com/it-hojo.pdf','POS・予約・在庫・ECなどITツール導入に使える（サンプル）。',
 true, false, array['IT','DX','POS','予約システム','EC'], array['DX','POS導入','在庫管理','予約システム','EC強化','AI導入','業務自動化','省力化'],
 '登録IT導入支援事業者のツールに限る（サンプル）。', true, '採択制', '中', 'サンプル', now()),
('省エネ設備導入補助金（空調更新・サンプル）','補助金','サンプル環境財団','財団系',
 array['愛知県','岐阜県'], array['全業種'], array[]::text[],
 '中小事業者', array['設備費','機械装置費'], '1/3', 200000, 1000000,
 current_date - 10, current_date + 10, '募集中', '郵送（サンプル）', '省エネ計算書、見積書',
 'https://example.com/shouene', null,'高効率空調・LEDなどへの更新が対象（サンプル）。締切が近い。',
 true, false, array['省エネ','空調','LED'], array['省エネ','空調設備','設備導入'],
 '中古設備は対象外（サンプル）。', true, '条件達成型', '低', 'サンプル', now()),
('人材開発支援助成金（研修・サンプル）','助成金','サンプル労働局','厚労省系',
 array['全国'], array['全業種'], array['株式会社','合同会社','一般社団法人'],
 '雇用保険適用事業所', array['研修費','人件費'], '45〜75%', null, 1000000,
 current_date - 60, null, '募集中', '労働局へ計画届提出（サンプル）', '訓練計画届、就業規則',
 'https://example.com/jinzai','https://example.com/jinzai.pdf','社員研修・OJTに使える助成金（サンプル）。計画届の事前提出が必要。',
 true, true, array['研修','人材育成','教育訓練'], array['社員教育','スタッフ採用'],
 '計画届提出前に開始した訓練は対象外（サンプル）。', false, '条件達成型', '高', 'サンプル', now()),
('地域づくり活動助成（イベント・サンプル）','助成金','サンプル地域財団','財団系',
 array['愛知県','名古屋市'], array['全業種'], array['一般社団法人','NPO法人','公益社団法人'],
 '非営利団体・地域団体', array['委託費','広告宣伝費','外注費'], '定額', null, 500000,
 current_date - 5, current_date + 60, '募集中', 'オンライン申請（サンプル）', '事業計画、収支予算書',
 'https://example.com/chiiki', null,'地域の健康・コミュニティイベント向け（サンプル）。',
 false, false, array['地域','イベント','健康','コミュニティ'], array['地域活動','健康支援','イベント開催'],
 '営利目的の事業は対象外（サンプル）。', false, '採択制', '低', 'サンプル', now()),
('EC・販路開拓支援補助金（サンプル）','補助金','サンプル県産業振興公社','自治体',
 array['岐阜県','愛知県'], array['食品','小売','EC','地域産品','製造業'], array[]::text[],
 '県内の中小事業者', array['広告宣伝費','システム導入費','委託費','開発費'], '1/2', 100000, 1500000,
 current_date - 15, current_date + 5, '締切間近', '電子申請（サンプル）', '販路開拓計画、見積書',
 'https://example.com/ec-hanro','https://example.com/ec-hanro.pdf','ECサイト構築・展示会出展・越境ECに使える（サンプル）。まもなく締切。',
 true, false, array['EC','販路開拓','越境EC','展示会'], array['EC強化','販路開拓','商品開発','広告宣伝','輸出','食品EC'],
 '県外事業者は対象外（サンプル）。', true, '採択制', '中', 'サンプル', now());
